theme = "github_dark"

[editor]
mouse = false
rulers = [100]
bufferline = "multiple"
cursorline = true
color-modes = true
auto-pairs = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
newline = "all"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
a = ["append_mode", "collapse_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
# X = ["extend_line_up", "extend_to_line_bounds"]
X = "extend_line_up"
J = "join_selections_space"

# Emacs style shortcuts
C-a = ["goto_line_start"]
C-e = ["goto_line_end"]
# C-v = ["half_page_down"]
# A-v = ["half_page_up"]

# VSCode style shortcuts
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
X = "extend_line_up"

[keys.normal.space]
o = "file_picker_in_current_buffer_directory"
"=" = ":format"
